# Generated by Django 4.0.8 on 2022-11-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank='true', default='https://poster.keepcalmandposters.com/default/5773497_keep_calm_there_is_nothing_here.png', upload_to='screenshots'),
        ),
    ]
